Fixing build error rake aborted! NoMethodError: undefined method `start_with?' for #<Array:0x007ffb81278c40> /.rvm/gems/ruby-2.0.0-p481/bundler/gems/Flow-70322b758ce8/lib/cocoa.rb:27:in `block (3 levels) in <top (required)>'